name: Build Status

on:
    pull_request:
    schedule:
        # run on sunday nights
        - cron: "0 0 * * 0"

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                # os: [ubuntu-latest, macos-latest, windows-latest]
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install pnpm
              run: |
                  npm install -g pnpm

            - name: Install dependencies
              run: |
                  pnpm install

            - name: Lint
              run: |
                  pnpm run lint

            - name: Build
              run: |
                  pnpm run build

            - name: Test
              run: |
                  pnpm run test
