name: Publish Package

on:
    release:
        types: [created]

jobs:
    deploy:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: |
                  pnpm install

            - name: Lint
              run: |
                  pnpm run lint

            - name: Build
              run: |
                  pnpm run build

            - name: Test
              run: |
                  pnpm run test

            - name: Publish
              run: |
                  npm publish
